//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacija.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MenuHighlight")]
        public global::System.Drawing.Color menuStripBoja {
            get {
                return ((global::System.Drawing.Color)(this["menuStripBoja"]));
            }
            set {
                this["menuStripBoja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBlue")]
        public global::System.Drawing.Color BojaPozadine {
            get {
                return ((global::System.Drawing.Color)(this["BojaPozadine"]));
            }
            set {
                this["BojaPozadine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BojaStatusMenija {
            get {
                return ((global::System.Drawing.Color)(this["BojaStatusMenija"]));
            }
            set {
                this["BojaStatusMenija"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MenuHighlight")]
        public global::System.Drawing.Color TabSkeniranje {
            get {
                return ((global::System.Drawing.Color)(this["TabSkeniranje"]));
            }
            set {
                this["TabSkeniranje"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MenuHighlight")]
        public global::System.Drawing.Color TabListaSkeniranja {
            get {
                return ((global::System.Drawing.Color)(this["TabListaSkeniranja"]));
            }
            set {
                this["TabListaSkeniranja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MenuHighlight")]
        public global::System.Drawing.Color TabOtvoriListu {
            get {
                return ((global::System.Drawing.Color)(this["TabOtvoriListu"]));
            }
            set {
                this["TabOtvoriListu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MenuHighlight")]
        public global::System.Drawing.Color TabMuzickiPlayer {
            get {
                return ((global::System.Drawing.Color)(this["TabMuzickiPlayer"]));
            }
            set {
                this["TabMuzickiPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MenuHighlight")]
        public global::System.Drawing.Color TabPdfCitac {
            get {
                return ((global::System.Drawing.Color)(this["TabPdfCitac"]));
            }
            set {
                this["TabPdfCitac"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MenuHighlight")]
        public global::System.Drawing.Color TabWebPretrazivac {
            get {
                return ((global::System.Drawing.Color)(this["TabWebPretrazivac"]));
            }
            set {
                this["TabWebPretrazivac"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MenuHighlight")]
        public global::System.Drawing.Color TabInformacije {
            get {
                return ((global::System.Drawing.Color)(this["TabInformacije"]));
            }
            set {
                this["TabInformacije"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string adresaListe {
            get {
                return ((string)(this["adresaListe"]));
            }
            set {
                this["adresaListe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string adresaPdfFajl {
            get {
                return ((string)(this["adresaPdfFajl"]));
            }
            set {
                this["adresaPdfFajl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nazivFoldera {
            get {
                return ((string)(this["nazivFoldera"]));
            }
            set {
                this["nazivFoldera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool folderPostoji {
            get {
                return ((bool)(this["folderPostoji"]));
            }
            set {
                this["folderPostoji"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string adresaZaPretrazivanje {
            get {
                return ((string)(this["adresaZaPretrazivanje"]));
            }
            set {
                this["adresaZaPretrazivanje"] = value;
            }
        }
    }
}
